version: '3.1'

networks:
  metric_net:

services:

  grafana:
    image: grafana/grafana
    networks:
      - metric_net
    ports:
      - 127.0.0.1:3000:3000
    user: "472:472"
    depends_on:
      - influxdb
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/

  renderer:
    image: grafana/grafana-image-renderer:latest
    environment:
      IGNORE_HTTPS_ERRORS: "true"
      TZ: ${TZ}
    networks:
      - metric_net
    # ports:
    #   - 8081

  influxdb:
    image: influxdb
    networks:
      - metric_net
    ports:
      - 127.0.0.1:4242:4242
      - 127.0.0.1:8086:8086
    volumes:
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ./influxdb/data:/var/lib/influxdb
    environment:
      INFLUXDB_HTTP_AUTH_ENABLED=false
      INFLUXDB_DB=${INFLUXDB_DB}
      INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      INFLUXDB_WRITE_USER=${INFLUXDB_WRITE_USER}
      INFLUXDB_WRITE_USER_PASSWORD=${INFLUXDB_WRITE_USER_PASSWORD}

    # influxdb memory tends to grow huge
    # XXX deploy:resources:limits:memory: does not work on podman-compose
    deploy:
      resources:
        limits:
          memory: 128M

  importer:
    image: debian:buster
    networks:
      - metric_net
    build:
